"""MediaPipe hand landmark indices and the skeleton we draw."""

WRIST = 0
THUMB_CMC, THUMB_MCP, THUMB_IP, THUMB_TIP = 1, 2, 3, 4
INDEX_MCP, INDEX_PIP, INDEX_DIP, INDEX_TIP = 5, 6, 7, 8
MIDDLE_MCP, MIDDLE_PIP, MIDDLE_DIP, MIDDLE_TIP = 9, 10, 11, 12
RING_MCP, RING_PIP, RING_DIP, RING_TIP = 13, 14, 15, 16
PINKY_MCP, PINKY_PIP, PINKY_DIP, PINKY_TIP = 17, 18, 19, 20

TIPS = (THUMB_TIP, INDEX_TIP, MIDDLE_TIP, RING_TIP, PINKY_TIP)
MCPS = (THUMB_CMC, INDEX_MCP, MIDDLE_MCP, RING_MCP, PINKY_MCP)
PIPS = (THUMB_MCP, INDEX_PIP, MIDDLE_PIP, RING_PIP, PINKY_PIP)

# Chains kept separate so the visualiser can taper each finger independently.
FINGERS = (
    (WRIST, THUMB_CMC, THUMB_MCP, THUMB_IP, THUMB_TIP),
    (INDEX_MCP, INDEX_PIP, INDEX_DIP, INDEX_TIP),
    (MIDDLE_MCP, MIDDLE_PIP, MIDDLE_DIP, MIDDLE_TIP),
    (RING_MCP, RING_PIP, RING_DIP, RING_TIP),
    (PINKY_MCP, PINKY_PIP, PINKY_DIP, PINKY_TIP),
)

# The palm outline, drawn as a closed low-alpha polygon.
PALM_LOOP = (WRIST, THUMB_CMC, INDEX_MCP, MIDDLE_MCP, RING_MCP, PINKY_MCP)

CONNECTIONS = []
for _chain in FINGERS:
    CONNECTIONS.extend(zip(_chain[:-1], _chain[1:]))
CONNECTIONS.extend([(INDEX_MCP, MIDDLE_MCP), (MIDDLE_MCP, RING_MCP),
                    (RING_MCP, PINKY_MCP), (WRIST, PINKY_MCP)])
